// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvr-6RCg5zCUYqKcO5AZu_7-gfZFngzeI',
    appId: '1:93310083558:web:b6c19c389292b404723627',
    messagingSenderId: '93310083558',
    projectId: 'curd-addproduct',
    authDomain: 'curd-addproduct.firebaseapp.com',
    storageBucket: 'curd-addproduct.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOTodV5VVdXPsQPY1pUuO42z-NMsjpNII',
    appId: '1:93310083558:android:c0a546038da28f08723627',
    messagingSenderId: '93310083558',
    projectId: 'curd-addproduct',
    storageBucket: 'curd-addproduct.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEgrHR1SCA4si8sq9PbRMcYfFrJ2VaCFM',
    appId: '1:93310083558:ios:a8c7d1decfb9591c723627',
    messagingSenderId: '93310083558',
    projectId: 'curd-addproduct',
    storageBucket: 'curd-addproduct.appspot.com',
    iosBundleId: 'com.example.cured2',
  );
}
